version: "3.8"

services:

  muteb-soc:

    build:
      context: ..

    container_name:
      muteb-soc

    restart:
      unless-stopped

    volumes:
      - ../logs:/opt/muteb-soc/logs
      - ../reports:/opt/muteb-soc/reports

    environment:

      - TZ=Asia/Riyadh

