

name: MUTEB SOC Enterprise CI



on:

  push:

    branches:

      - main


  pull_request:

    branches:

      - main





jobs:



  backend-test:


    name: Backend Security Test


    runs-on: ubuntu-latest



    steps:


      - name: Checkout

        uses: actions/checkout@v4



      - name: Setup Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.12"



      - name: Install Backend Dependencies

        run: |

          cd backend

          pip install -r requirements.txt



      - name: Python Syntax Check

        run: |

          cd backend

          python -m compileall .





      - name: Backend Health Test

        run: |

          cd backend

          python -c "import app; print('Backend OK')"







  frontend-test:


    name: Frontend Build Test


    runs-on: ubuntu-latest



    steps:


      - name: Checkout

        uses: actions/checkout@v4



      - name: Setup Node

        uses: actions/setup-node@v4

        with:

          node-version: "18"



      - name: Install Frontend

        run: |


          cd frontend

          npm install



      - name: Build Frontend

        run: |


          cd frontend

          npm run build







  docker-test:


    name: Docker Build Test


    runs-on: ubuntu-latest



    steps:


      - name: Checkout

        uses: actions/checkout@v4



      - name: Build Containers

        run: |


          docker compose build





