

name: MUTEB Security Scan



on:


  workflow_dispatch:



jobs:


 security:


  runs-on: ubuntu-latest



  steps:



  - uses: actions/checkout@v4



  - name: Check Sensitive Files

    run: |


      grep -RniE "password=|secret=|api_key=" . \
      --exclude-dir=node_modules \
      --exclude-dir=.git \
      || true



  - name: Complete

    run: |

      echo "Security Review Completed"



